channel_cfg = dict(
    dataset_channel=[
        [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
        ],
    ],
    dataset_joints=17,
    inference_channel=[
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
    ],
    num_output_channels=17)
checkpoint_config = dict(interval=10)
data = dict(
    samples_per_gpu=32,
    test=dict(
        ann_file='data/coco/annotations/person_keypoints_val2017.json',
        data_cfg=dict(
            bbox_file=
            'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json',
            dataset_channel=[
                [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                ],
            ],
            det_bbox_thr=0.0,
            heatmap_size=[
                48,
                64,
            ],
            image_size=[
                192,
                256,
            ],
            inference_channel=[
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
            ],
            nms_thr=1.0,
            num_joints=17,
            num_output_channels=17,
            oks_thr=0.9,
            soft_nms=False,
            use_gt_bbox=False,
            vis_thr=0.2),
        dataset_info=dict(
            dataset_name='coco',
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.2,
                1.2,
                1.5,
                1.5,
                1.0,
                1.0,
                1.2,
                1.2,
                1.5,
                1.5,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=0,
                    name='nose',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=1,
                    name='left_eye',
                    swap='right_eye',
                    type='upper'),
                10:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=10,
                    name='right_wrist',
                    swap='left_wrist',
                    type='upper'),
                11:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=11,
                    name='left_hip',
                    swap='right_hip',
                    type='lower'),
                12:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=12,
                    name='right_hip',
                    swap='left_hip',
                    type='lower'),
                13:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=13,
                    name='left_knee',
                    swap='right_knee',
                    type='lower'),
                14:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=14,
                    name='right_knee',
                    swap='left_knee',
                    type='lower'),
                15:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=15,
                    name='left_ankle',
                    swap='right_ankle',
                    type='lower'),
                16:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=16,
                    name='right_ankle',
                    swap='left_ankle',
                    type='lower'),
                2:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=2,
                    name='right_eye',
                    swap='left_eye',
                    type='upper'),
                3:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=3,
                    name='left_ear',
                    swap='right_ear',
                    type='upper'),
                4:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=4,
                    name='right_ear',
                    swap='left_ear',
                    type='upper'),
                5:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=5,
                    name='left_shoulder',
                    swap='right_shoulder',
                    type='upper'),
                6:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=6,
                    name='right_shoulder',
                    swap='left_shoulder',
                    type='upper'),
                7:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=7,
                    name='left_elbow',
                    swap='right_elbow',
                    type='upper'),
                8:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=8,
                    name='right_elbow',
                    swap='left_elbow',
                    type='upper'),
                9:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=9,
                    name='left_wrist',
                    swap='right_wrist',
                    type='upper')
            }),
            paper_info=dict(
                author=
                "Lin, Tsung-Yi and Maire, Michael and Belongie, Serge and Hays, James and Perona, Pietro and Ramanan, Deva and Doll{\\'a}r, Piotr and Zitnick, C Lawrence",
                container='European conference on computer vision',
                homepage='http://cocodataset.org/',
                title='Microsoft coco: Common objects in context',
                year='2014'),
            sigmas=[
                0.026,
                0.025,
                0.025,
                0.035,
                0.035,
                0.079,
                0.079,
                0.072,
                0.072,
                0.062,
                0.062,
                0.107,
                0.107,
                0.087,
                0.087,
                0.089,
                0.089,
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=0,
                    link=(
                        'left_ankle',
                        'left_knee',
                    )),
                1:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=1,
                    link=(
                        'left_knee',
                        'left_hip',
                    )),
                10:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=10,
                    link=(
                        'left_elbow',
                        'left_wrist',
                    )),
                11:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=11,
                    link=(
                        'right_elbow',
                        'right_wrist',
                    )),
                12:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=12,
                    link=(
                        'left_eye',
                        'right_eye',
                    )),
                13:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ], id=13, link=(
                        'nose',
                        'left_eye',
                    )),
                14:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=14,
                    link=(
                        'nose',
                        'right_eye',
                    )),
                15:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=15,
                    link=(
                        'left_eye',
                        'left_ear',
                    )),
                16:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=16,
                    link=(
                        'right_eye',
                        'right_ear',
                    )),
                17:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=17,
                    link=(
                        'left_ear',
                        'left_shoulder',
                    )),
                18:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=18,
                    link=(
                        'right_ear',
                        'right_shoulder',
                    )),
                2:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=2,
                    link=(
                        'right_ankle',
                        'right_knee',
                    )),
                3:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=3,
                    link=(
                        'right_knee',
                        'right_hip',
                    )),
                4:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=4,
                    link=(
                        'left_hip',
                        'right_hip',
                    )),
                5:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=5,
                    link=(
                        'left_shoulder',
                        'left_hip',
                    )),
                6:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=6,
                    link=(
                        'right_shoulder',
                        'right_hip',
                    )),
                7:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=7,
                    link=(
                        'left_shoulder',
                        'right_shoulder',
                    )),
                8:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=8,
                    link=(
                        'left_shoulder',
                        'left_elbow',
                    )),
                9:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=9,
                    link=(
                        'right_shoulder',
                        'right_elbow',
                    ))
            })),
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(padding=1.25, type='TopDownGetBboxCenterScale'),
            dict(type='TopDownAffine'),
            dict(type='ToTensor'),
            dict(
                mean=[
                    0.485,
                    0.456,
                    0.406,
                ],
                std=[
                    0.229,
                    0.224,
                    0.225,
                ],
                type='NormalizeTensor'),
            dict(
                keys=[
                    'img',
                ],
                meta_keys=[
                    'image_file',
                    'center',
                    'scale',
                    'rotation',
                    'bbox_score',
                    'flip_pairs',
                ],
                type='Collect'),
        ],
        type='TopDownCocoDataset'),
    test_dataloader=dict(samples_per_gpu=32),
    train=dict(
        ann_file='data/coco/annotations/person_keypoints_train2017.json',
        data_cfg=dict(
            bbox_file=
            'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json',
            dataset_channel=[
                [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                ],
            ],
            det_bbox_thr=0.0,
            heatmap_size=[
                48,
                64,
            ],
            image_size=[
                192,
                256,
            ],
            inference_channel=[
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
            ],
            nms_thr=1.0,
            num_joints=17,
            num_output_channels=17,
            oks_thr=0.9,
            soft_nms=False,
            use_gt_bbox=False,
            vis_thr=0.2),
        dataset_info=dict(
            dataset_name='coco',
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.2,
                1.2,
                1.5,
                1.5,
                1.0,
                1.0,
                1.2,
                1.2,
                1.5,
                1.5,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=0,
                    name='nose',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=1,
                    name='left_eye',
                    swap='right_eye',
                    type='upper'),
                10:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=10,
                    name='right_wrist',
                    swap='left_wrist',
                    type='upper'),
                11:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=11,
                    name='left_hip',
                    swap='right_hip',
                    type='lower'),
                12:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=12,
                    name='right_hip',
                    swap='left_hip',
                    type='lower'),
                13:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=13,
                    name='left_knee',
                    swap='right_knee',
                    type='lower'),
                14:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=14,
                    name='right_knee',
                    swap='left_knee',
                    type='lower'),
                15:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=15,
                    name='left_ankle',
                    swap='right_ankle',
                    type='lower'),
                16:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=16,
                    name='right_ankle',
                    swap='left_ankle',
                    type='lower'),
                2:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=2,
                    name='right_eye',
                    swap='left_eye',
                    type='upper'),
                3:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=3,
                    name='left_ear',
                    swap='right_ear',
                    type='upper'),
                4:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=4,
                    name='right_ear',
                    swap='left_ear',
                    type='upper'),
                5:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=5,
                    name='left_shoulder',
                    swap='right_shoulder',
                    type='upper'),
                6:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=6,
                    name='right_shoulder',
                    swap='left_shoulder',
                    type='upper'),
                7:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=7,
                    name='left_elbow',
                    swap='right_elbow',
                    type='upper'),
                8:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=8,
                    name='right_elbow',
                    swap='left_elbow',
                    type='upper'),
                9:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=9,
                    name='left_wrist',
                    swap='right_wrist',
                    type='upper')
            }),
            paper_info=dict(
                author=
                "Lin, Tsung-Yi and Maire, Michael and Belongie, Serge and Hays, James and Perona, Pietro and Ramanan, Deva and Doll{\\'a}r, Piotr and Zitnick, C Lawrence",
                container='European conference on computer vision',
                homepage='http://cocodataset.org/',
                title='Microsoft coco: Common objects in context',
                year='2014'),
            sigmas=[
                0.026,
                0.025,
                0.025,
                0.035,
                0.035,
                0.079,
                0.079,
                0.072,
                0.072,
                0.062,
                0.062,
                0.107,
                0.107,
                0.087,
                0.087,
                0.089,
                0.089,
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=0,
                    link=(
                        'left_ankle',
                        'left_knee',
                    )),
                1:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=1,
                    link=(
                        'left_knee',
                        'left_hip',
                    )),
                10:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=10,
                    link=(
                        'left_elbow',
                        'left_wrist',
                    )),
                11:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=11,
                    link=(
                        'right_elbow',
                        'right_wrist',
                    )),
                12:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=12,
                    link=(
                        'left_eye',
                        'right_eye',
                    )),
                13:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ], id=13, link=(
                        'nose',
                        'left_eye',
                    )),
                14:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=14,
                    link=(
                        'nose',
                        'right_eye',
                    )),
                15:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=15,
                    link=(
                        'left_eye',
                        'left_ear',
                    )),
                16:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=16,
                    link=(
                        'right_eye',
                        'right_ear',
                    )),
                17:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=17,
                    link=(
                        'left_ear',
                        'left_shoulder',
                    )),
                18:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=18,
                    link=(
                        'right_ear',
                        'right_shoulder',
                    )),
                2:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=2,
                    link=(
                        'right_ankle',
                        'right_knee',
                    )),
                3:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=3,
                    link=(
                        'right_knee',
                        'right_hip',
                    )),
                4:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=4,
                    link=(
                        'left_hip',
                        'right_hip',
                    )),
                5:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=5,
                    link=(
                        'left_shoulder',
                        'left_hip',
                    )),
                6:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=6,
                    link=(
                        'right_shoulder',
                        'right_hip',
                    )),
                7:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=7,
                    link=(
                        'left_shoulder',
                        'right_shoulder',
                    )),
                8:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=8,
                    link=(
                        'left_shoulder',
                        'left_elbow',
                    )),
                9:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=9,
                    link=(
                        'right_shoulder',
                        'right_elbow',
                    ))
            })),
        img_prefix='data/coco/train2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(padding=1.25, type='TopDownGetBboxCenterScale'),
            dict(
                prob=0.3,
                shift_factor=0.16,
                type='TopDownRandomShiftBboxCenter'),
            dict(flip_prob=0.5, type='TopDownRandomFlip'),
            dict(
                num_joints_half_body=8,
                prob_half_body=0.3,
                type='TopDownHalfBodyTransform'),
            dict(
                rot_factor=40,
                scale_factor=0.5,
                type='TopDownGetRandomScaleRotation'),
            dict(type='TopDownAffine'),
            dict(type='ToTensor'),
            dict(
                mean=[
                    0.485,
                    0.456,
                    0.406,
                ],
                std=[
                    0.229,
                    0.224,
                    0.225,
                ],
                type='NormalizeTensor'),
            dict(sigma=2, type='TopDownGenerateTarget'),
            dict(
                keys=[
                    'img',
                    'target',
                    'target_weight',
                ],
                meta_keys=[
                    'image_file',
                    'joints_3d',
                    'joints_3d_visible',
                    'center',
                    'scale',
                    'rotation',
                    'bbox_score',
                    'flip_pairs',
                ],
                type='Collect'),
        ],
        type='TopDownCocoDataset'),
    val=dict(
        ann_file='data/coco/annotations/person_keypoints_val2017.json',
        data_cfg=dict(
            bbox_file=
            'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json',
            dataset_channel=[
                [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                ],
            ],
            det_bbox_thr=0.0,
            heatmap_size=[
                48,
                64,
            ],
            image_size=[
                192,
                256,
            ],
            inference_channel=[
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
            ],
            nms_thr=1.0,
            num_joints=17,
            num_output_channels=17,
            oks_thr=0.9,
            soft_nms=False,
            use_gt_bbox=False,
            vis_thr=0.2),
        dataset_info=dict(
            dataset_name='coco',
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.2,
                1.2,
                1.5,
                1.5,
                1.0,
                1.0,
                1.2,
                1.2,
                1.5,
                1.5,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=0,
                    name='nose',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=1,
                    name='left_eye',
                    swap='right_eye',
                    type='upper'),
                10:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=10,
                    name='right_wrist',
                    swap='left_wrist',
                    type='upper'),
                11:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=11,
                    name='left_hip',
                    swap='right_hip',
                    type='lower'),
                12:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=12,
                    name='right_hip',
                    swap='left_hip',
                    type='lower'),
                13:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=13,
                    name='left_knee',
                    swap='right_knee',
                    type='lower'),
                14:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=14,
                    name='right_knee',
                    swap='left_knee',
                    type='lower'),
                15:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=15,
                    name='left_ankle',
                    swap='right_ankle',
                    type='lower'),
                16:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=16,
                    name='right_ankle',
                    swap='left_ankle',
                    type='lower'),
                2:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=2,
                    name='right_eye',
                    swap='left_eye',
                    type='upper'),
                3:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=3,
                    name='left_ear',
                    swap='right_ear',
                    type='upper'),
                4:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=4,
                    name='right_ear',
                    swap='left_ear',
                    type='upper'),
                5:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=5,
                    name='left_shoulder',
                    swap='right_shoulder',
                    type='upper'),
                6:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=6,
                    name='right_shoulder',
                    swap='left_shoulder',
                    type='upper'),
                7:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=7,
                    name='left_elbow',
                    swap='right_elbow',
                    type='upper'),
                8:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=8,
                    name='right_elbow',
                    swap='left_elbow',
                    type='upper'),
                9:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=9,
                    name='left_wrist',
                    swap='right_wrist',
                    type='upper')
            }),
            paper_info=dict(
                author=
                "Lin, Tsung-Yi and Maire, Michael and Belongie, Serge and Hays, James and Perona, Pietro and Ramanan, Deva and Doll{\\'a}r, Piotr and Zitnick, C Lawrence",
                container='European conference on computer vision',
                homepage='http://cocodataset.org/',
                title='Microsoft coco: Common objects in context',
                year='2014'),
            sigmas=[
                0.026,
                0.025,
                0.025,
                0.035,
                0.035,
                0.079,
                0.079,
                0.072,
                0.072,
                0.062,
                0.062,
                0.107,
                0.107,
                0.087,
                0.087,
                0.089,
                0.089,
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=0,
                    link=(
                        'left_ankle',
                        'left_knee',
                    )),
                1:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=1,
                    link=(
                        'left_knee',
                        'left_hip',
                    )),
                10:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=10,
                    link=(
                        'left_elbow',
                        'left_wrist',
                    )),
                11:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=11,
                    link=(
                        'right_elbow',
                        'right_wrist',
                    )),
                12:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=12,
                    link=(
                        'left_eye',
                        'right_eye',
                    )),
                13:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ], id=13, link=(
                        'nose',
                        'left_eye',
                    )),
                14:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=14,
                    link=(
                        'nose',
                        'right_eye',
                    )),
                15:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=15,
                    link=(
                        'left_eye',
                        'left_ear',
                    )),
                16:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=16,
                    link=(
                        'right_eye',
                        'right_ear',
                    )),
                17:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=17,
                    link=(
                        'left_ear',
                        'left_shoulder',
                    )),
                18:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=18,
                    link=(
                        'right_ear',
                        'right_shoulder',
                    )),
                2:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=2,
                    link=(
                        'right_ankle',
                        'right_knee',
                    )),
                3:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=3,
                    link=(
                        'right_knee',
                        'right_hip',
                    )),
                4:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=4,
                    link=(
                        'left_hip',
                        'right_hip',
                    )),
                5:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=5,
                    link=(
                        'left_shoulder',
                        'left_hip',
                    )),
                6:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=6,
                    link=(
                        'right_shoulder',
                        'right_hip',
                    )),
                7:
                dict(
                    color=[
                        51,
                        153,
                        255,
                    ],
                    id=7,
                    link=(
                        'left_shoulder',
                        'right_shoulder',
                    )),
                8:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=8,
                    link=(
                        'left_shoulder',
                        'left_elbow',
                    )),
                9:
                dict(
                    color=[
                        255,
                        128,
                        0,
                    ],
                    id=9,
                    link=(
                        'right_shoulder',
                        'right_elbow',
                    ))
            })),
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(padding=1.25, type='TopDownGetBboxCenterScale'),
            dict(type='TopDownAffine'),
            dict(type='ToTensor'),
            dict(
                mean=[
                    0.485,
                    0.456,
                    0.406,
                ],
                std=[
                    0.229,
                    0.224,
                    0.225,
                ],
                type='NormalizeTensor'),
            dict(
                keys=[
                    'img',
                ],
                meta_keys=[
                    'image_file',
                    'center',
                    'scale',
                    'rotation',
                    'bbox_score',
                    'flip_pairs',
                ],
                type='Collect'),
        ],
        type='TopDownCocoDataset'),
    val_dataloader=dict(samples_per_gpu=32),
    workers_per_gpu=2)
data_cfg = dict(
    bbox_file=
    'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json',
    dataset_channel=[
        [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
        ],
    ],
    det_bbox_thr=0.0,
    heatmap_size=[
        48,
        64,
    ],
    image_size=[
        192,
        256,
    ],
    inference_channel=[
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
    ],
    nms_thr=1.0,
    num_joints=17,
    num_output_channels=17,
    oks_thr=0.9,
    soft_nms=False,
    use_gt_bbox=False,
    vis_thr=0.2)
data_root = 'data/coco'
dataset_info = dict(
    dataset_name='coco',
    joint_weights=[
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.2,
        1.2,
        1.5,
        1.5,
        1.0,
        1.0,
        1.2,
        1.2,
        1.5,
        1.5,
    ],
    keypoint_info=dict({
        0:
        dict(color=[
            51,
            153,
            255,
        ], id=0, name='nose', swap='', type='upper'),
        1:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=1,
            name='left_eye',
            swap='right_eye',
            type='upper'),
        10:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=10,
            name='right_wrist',
            swap='left_wrist',
            type='upper'),
        11:
        dict(
            color=[
                0,
                255,
                0,
            ],
            id=11,
            name='left_hip',
            swap='right_hip',
            type='lower'),
        12:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=12,
            name='right_hip',
            swap='left_hip',
            type='lower'),
        13:
        dict(
            color=[
                0,
                255,
                0,
            ],
            id=13,
            name='left_knee',
            swap='right_knee',
            type='lower'),
        14:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=14,
            name='right_knee',
            swap='left_knee',
            type='lower'),
        15:
        dict(
            color=[
                0,
                255,
                0,
            ],
            id=15,
            name='left_ankle',
            swap='right_ankle',
            type='lower'),
        16:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=16,
            name='right_ankle',
            swap='left_ankle',
            type='lower'),
        2:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=2,
            name='right_eye',
            swap='left_eye',
            type='upper'),
        3:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=3,
            name='left_ear',
            swap='right_ear',
            type='upper'),
        4:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=4,
            name='right_ear',
            swap='left_ear',
            type='upper'),
        5:
        dict(
            color=[
                0,
                255,
                0,
            ],
            id=5,
            name='left_shoulder',
            swap='right_shoulder',
            type='upper'),
        6:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=6,
            name='right_shoulder',
            swap='left_shoulder',
            type='upper'),
        7:
        dict(
            color=[
                0,
                255,
                0,
            ],
            id=7,
            name='left_elbow',
            swap='right_elbow',
            type='upper'),
        8:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=8,
            name='right_elbow',
            swap='left_elbow',
            type='upper'),
        9:
        dict(
            color=[
                0,
                255,
                0,
            ],
            id=9,
            name='left_wrist',
            swap='right_wrist',
            type='upper')
    }),
    paper_info=dict(
        author=
        "Lin, Tsung-Yi and Maire, Michael and Belongie, Serge and Hays, James and Perona, Pietro and Ramanan, Deva and Doll{\\'a}r, Piotr and Zitnick, C Lawrence",
        container='European conference on computer vision',
        homepage='http://cocodataset.org/',
        title='Microsoft coco: Common objects in context',
        year='2014'),
    sigmas=[
        0.026,
        0.025,
        0.025,
        0.035,
        0.035,
        0.079,
        0.079,
        0.072,
        0.072,
        0.062,
        0.062,
        0.107,
        0.107,
        0.087,
        0.087,
        0.089,
        0.089,
    ],
    skeleton_info=dict({
        0:
        dict(color=[
            0,
            255,
            0,
        ], id=0, link=(
            'left_ankle',
            'left_knee',
        )),
        1:
        dict(color=[
            0,
            255,
            0,
        ], id=1, link=(
            'left_knee',
            'left_hip',
        )),
        10:
        dict(color=[
            0,
            255,
            0,
        ], id=10, link=(
            'left_elbow',
            'left_wrist',
        )),
        11:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=11,
            link=(
                'right_elbow',
                'right_wrist',
            )),
        12:
        dict(color=[
            51,
            153,
            255,
        ], id=12, link=(
            'left_eye',
            'right_eye',
        )),
        13:
        dict(color=[
            51,
            153,
            255,
        ], id=13, link=(
            'nose',
            'left_eye',
        )),
        14:
        dict(color=[
            51,
            153,
            255,
        ], id=14, link=(
            'nose',
            'right_eye',
        )),
        15:
        dict(color=[
            51,
            153,
            255,
        ], id=15, link=(
            'left_eye',
            'left_ear',
        )),
        16:
        dict(color=[
            51,
            153,
            255,
        ], id=16, link=(
            'right_eye',
            'right_ear',
        )),
        17:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=17,
            link=(
                'left_ear',
                'left_shoulder',
            )),
        18:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=18,
            link=(
                'right_ear',
                'right_shoulder',
            )),
        2:
        dict(
            color=[
                255,
                128,
                0,
            ], id=2, link=(
                'right_ankle',
                'right_knee',
            )),
        3:
        dict(color=[
            255,
            128,
            0,
        ], id=3, link=(
            'right_knee',
            'right_hip',
        )),
        4:
        dict(color=[
            51,
            153,
            255,
        ], id=4, link=(
            'left_hip',
            'right_hip',
        )),
        5:
        dict(
            color=[
                51,
                153,
                255,
            ], id=5, link=(
                'left_shoulder',
                'left_hip',
            )),
        6:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=6,
            link=(
                'right_shoulder',
                'right_hip',
            )),
        7:
        dict(
            color=[
                51,
                153,
                255,
            ],
            id=7,
            link=(
                'left_shoulder',
                'right_shoulder',
            )),
        8:
        dict(
            color=[
                0,
                255,
                0,
            ], id=8, link=(
                'left_shoulder',
                'left_elbow',
            )),
        9:
        dict(
            color=[
                255,
                128,
                0,
            ],
            id=9,
            link=(
                'right_shoulder',
                'right_elbow',
            ))
    }))
dist_params = dict(backend='nccl')
evaluation = dict(interval=10, metric='mAP', save_best='AP')
load_from = None
log_config = dict(
    hooks=[
        dict(type='TextLoggerHook'),
    ], interval=50)
log_level = 'INFO'
lr_config = dict(
    policy='step',
    step=[
        170,
        200,
    ],
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001)
model = dict(
    backbone=dict(
        extra=dict(
            stage1=dict(
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_branches=1,
                num_channels=(64, ),
                num_modules=1),
            stage2=dict(
                block='BASIC',
                num_blocks=(
                    4,
                    4,
                ),
                num_branches=2,
                num_channels=(
                    48,
                    96,
                ),
                num_modules=1),
            stage3=dict(
                block='BASIC',
                num_blocks=(
                    4,
                    4,
                    4,
                ),
                num_branches=3,
                num_channels=(
                    48,
                    96,
                    192,
                ),
                num_modules=4),
            stage4=dict(
                block='BASIC',
                num_blocks=(
                    4,
                    4,
                    4,
                    4,
                ),
                num_branches=4,
                num_channels=(
                    48,
                    96,
                    192,
                    384,
                ),
                num_modules=3)),
        in_channels=3,
        type='HRNet'),
    keypoint_head=dict(
        extra=dict(final_conv_kernel=1),
        in_channels=48,
        loss_keypoint=dict(type='JointsMSELoss', use_target_weight=True),
        num_deconv_layers=0,
        out_channels=17,
        type='TopdownHeatmapSimpleHead'),
    pretrained=
    'https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w48-8ef0771d.pth',
    test_cfg=dict(
        flip_test=True,
        modulate_kernel=11,
        post_process='default',
        shift_heatmap=True),
    train_cfg=dict(),
    type='TopDown')
mp_start_method = 'fork'
opencv_num_threads = 0
optimizer = dict(lr=0.0005, type='Adam')
optimizer_config = dict(grad_clip=None)
resume_from = None
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(padding=1.25, type='TopDownGetBboxCenterScale'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        mean=[
            0.485,
            0.456,
            0.406,
        ],
        std=[
            0.229,
            0.224,
            0.225,
        ],
        type='NormalizeTensor'),
    dict(
        keys=[
            'img',
        ],
        meta_keys=[
            'image_file',
            'center',
            'scale',
            'rotation',
            'bbox_score',
            'flip_pairs',
        ],
        type='Collect'),
]
total_epochs = 210
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(padding=1.25, type='TopDownGetBboxCenterScale'),
    dict(prob=0.3, shift_factor=0.16, type='TopDownRandomShiftBboxCenter'),
    dict(flip_prob=0.5, type='TopDownRandomFlip'),
    dict(
        num_joints_half_body=8,
        prob_half_body=0.3,
        type='TopDownHalfBodyTransform'),
    dict(
        rot_factor=40, scale_factor=0.5, type='TopDownGetRandomScaleRotation'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        mean=[
            0.485,
            0.456,
            0.406,
        ],
        std=[
            0.229,
            0.224,
            0.225,
        ],
        type='NormalizeTensor'),
    dict(sigma=2, type='TopDownGenerateTarget'),
    dict(
        keys=[
            'img',
            'target',
            'target_weight',
        ],
        meta_keys=[
            'image_file',
            'joints_3d',
            'joints_3d_visible',
            'center',
            'scale',
            'rotation',
            'bbox_score',
            'flip_pairs',
        ],
        type='Collect'),
]
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(padding=1.25, type='TopDownGetBboxCenterScale'),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        mean=[
            0.485,
            0.456,
            0.406,
        ],
        std=[
            0.229,
            0.224,
            0.225,
        ],
        type='NormalizeTensor'),
    dict(
        keys=[
            'img',
        ],
        meta_keys=[
            'image_file',
            'center',
            'scale',
            'rotation',
            'bbox_score',
            'flip_pairs',
        ],
        type='Collect'),
]
workflow = [
    (
        'train',
        1,
    ),
]
