#!/usr/bin/env python3
"""
Feature Verification Script

Compares the features generated by the test pipeline against the expected features
from the training model to ensure consistency.
"""

import sys
import json
from pathlib import Path
import pandas as pd

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / 'src'))

from rpe_pipeline import RPEPredictor


def load_expected_features():
    """Load expected features from trained model metadata"""
    metadata_path = Path('src/Train_Outputs/ensemble_metadata.json')
    if not metadata_path.exists():
        print(f"❌ Model metadata not found: {metadata_path}")
        print("   Run training first: python src/LGBM_Regressor/LGBMMod2_Ensemble.py")
        return None
    
    with open(metadata_path, 'r') as f:
        metadata = json.load(f)
    
    return metadata['feature_columns']


def verify_feature_generation(video_path=None, movement='Squat'):
    """
    Verify that the feature extraction pipeline generates all expected features.
    
    If video_path is None, uses a mock example to show feature structure.
    """
    print("="*70)
    print("FEATURE VERIFICATION")
    print("="*70)
    
    # Load expected features from model
    expected_features = load_expected_features()
    if not expected_features:
        return False
    
    print(f"\n✓ Loaded model metadata")
    print(f"   Expected features: {len(expected_features)}")
    
    # Show expected features
    print("\n📋 Expected Features from Training Model:")
    print("-" * 70)
    
    # Group features by category
    base_features = []
    au_features = []
    engineered_features = []
    
    for feat in expected_features:
        if 'AU' in feat and '_max' in feat:
            au_features.append(feat)
        elif 'AU' in feat or 'interaction' in feat or '_x_' in feat or 'per_rep' in feat or 'quality' in feat or 'strain' in feat or 'tempo' in feat or feat.endswith('_sq'):
            engineered_features.append(feat)
        else:
            base_features.append(feat)
    
    print(f"\n1. Base Features ({len(base_features)}):")
    for feat in base_features:
        print(f"   - {feat}")
    
    print(f"\n2. AU Max Features ({len(au_features)}):")
    for feat in au_features:
        print(f"   - {feat}")
    
    print(f"\n3. Engineered Features ({len(engineered_features)}):")
    for feat in engineered_features:
        print(f"   - {feat}")
    
    # If video provided, test actual extraction
    if video_path and Path(video_path).exists():
        print("\n" + "="*70)
        print("TESTING FEATURE EXTRACTION")
        print("="*70)
        print(f"\n📹 Video: {Path(video_path).name}")
        print(f"   Movement: {movement}")
        print("\nExtracting features (this may take a few minutes)...\n")
        
        try:
            predictor = RPEPredictor(verbose=False)
            extraction_results = predictor.extract_all_features(video_path, movement)
            extracted_features = extraction_results['combined']
            
            print("✓ Feature extraction complete")
            print(f"   Extracted features: {len(extracted_features)}")
            
            # Compare extracted vs expected
            print("\n" + "="*70)
            print("FEATURE COMPARISON")
            print("="*70)
            
            missing_features = []
            extra_features = []
            matched_features = []
            
            for feat in expected_features:
                if feat in extracted_features:
                    matched_features.append(feat)
                else:
                    missing_features.append(feat)
            
            for feat in extracted_features:
                if feat not in expected_features:
                    extra_features.append(feat)
            
            # Results
            print(f"\n✓ Matched Features: {len(matched_features)}/{len(expected_features)}")
            
            if missing_features:
                print(f"\n❌ Missing Features ({len(missing_features)}):")
                for feat in missing_features:
                    print(f"   - {feat}")
            else:
                print(f"\n✓ All expected features present!")
            
            if extra_features:
                print(f"\n⚠️  Extra Features ({len(extra_features)}) (not in training):")
                for feat in extra_features[:10]:  # Show first 10
                    print(f"   - {feat}")
                if len(extra_features) > 10:
                    print(f"   ... and {len(extra_features) - 10} more")
            
            # Show some example values
            print(f"\n📊 Sample Feature Values:")
            print("-" * 70)
            sample_features = [
                'rep_count', 'rep_change_s', 'd_value', 'detection_rate',
                'AU04_max', 'AU07_max', 'AU_sum', 'quality_score',
                'body_face_strain', 'avg_rep_duration', 'Lift_Type_Code'
            ]
            
            for feat in sample_features:
                if feat in extracted_features:
                    value = extracted_features[feat]
                    print(f"   {feat:.<30} {value:.4f}" if isinstance(value, float) else f"   {feat:.<30} {value}")
            
            # Final verdict
            print("\n" + "="*70)
            if not missing_features:
                print("✅ VERIFICATION PASSED")
                print("   All expected features are generated correctly!")
                print("   The test pipeline matches the training pipeline.")
                return True
            else:
                print("❌ VERIFICATION FAILED")
                print(f"   {len(missing_features)} features are missing from extraction.")
                print("   The pipeline may need updates to match training.")
                return False
                
        except Exception as e:
            print(f"\n❌ Error during feature extraction: {e}")
            import traceback
            traceback.print_exc()
            return False
    
    else:
        print("\n" + "="*70)
        print("ℹ️  No video provided - showing expected features only")
        print("   Run with: python verify_features.py path/to/video.mp4 Squat")
        print("="*70)
        return None


def main():
    """Run feature verification"""
    if len(sys.argv) >= 2:
        video_path = sys.argv[1]
        movement = sys.argv[2] if len(sys.argv) >= 3 else 'Squat'
    else:
        video_path = None
        movement = 'Squat'
        print("\nUsage:")
        print(f"   python {sys.argv[0]} path/to/video.mp4 [movement]")
        print(f"\nShowing expected features without testing extraction...\n")
    
    result = verify_feature_generation(video_path, movement)
    
    if result is True:
        return 0
    elif result is False:
        return 1
    else:
        return 0  # Just showing info


if __name__ == '__main__':
    sys.exit(main())
